#=================================================================================================================================================
#herpes_zoster_c00_age
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fhir: <http://hl7.org/fhir/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX w5: <http://hl7.org/fhir/w5#>
PREFIX example: <http://example.org/>
PREFIX example_graph: <http://example.org/graphs/>
PREFIX fc: <http://fhircat.org/>

INSERT {
    GRAPH fc:herpes_zoster_c00_age {
			?patient fc:age ?age.
    }
}

    WHERE {
    GRAPH fc:emergeCohort2{
        fc:cohort fc:contains ?patient
    }
	
    SERVICE <http://localhost:8080/sparql>
        
        { 
            ?patient a fhir:Patient;
            fhir:Resource.id [ fhir:value ?patient_id];
			fhir:Patient.birthDate [ fhir:value ?birthdate].

    } 
#obtain the year of birth and the current year and calculate the age
    BIND ((xsd:integer(SUBSTR(STR(NOW()), 1, 4)) - xsd:integer(SUBSTR(STR(?birthdate), 1, 4))) AS ?age )
    } 