#===============================================================================================================================================================================================================================================================================================================
#c13 pmhNtExistence is from nlp source. not suitable for our case